#!/bin/sh
#
# Start music....
#

start() {
      printf "Starting music: "
      cd /game
      python3 start.py
      python3 rasPYbot.py
}

stop() {
      printf "stopping music: "
}

case "$1" in
    start)
    start
    ;;
    stop)
    stop
    ;;
    restart|reload)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
