#!/bin/sh
#
# Start gif ....
#

start() {
      start-stop-daemon -S -q -m -b -p /var/run/splash.pid \
            sh /etc/gif.sh
      [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    start-stop-daemon -K -q -p /var/run/splash.pid \
              sh /etc/gif.sh
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
    start)
    start
    ;;
    stop)
    stop
    ;;
    restart|reload)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?