FBCP_VERSION = origin/master
FBCP_SITE = https://github.com/alexandre-humbert/fbcp-ili9341.git
FBCP_SITE_METHOD = git
FBCP_CONF_OPTS = -DILI9341=ON -DGPIO_TFT_BACKLIGHT=12 -DGPIO_TFT_DATA_CONTROL=24 -DGPIO_TFT_RESET_PIN=23 -DSPI_BUS_CLOCK_DIVISOR=8 -DSINGLE_CORE_BOARD=ON -DARMV6Z=ON -DSTATISTICS=0

$(eval $(cmake-package))
